---
title: "social bots"
author: "jiehan liu"
date: "4/15/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(stringr)
library(bit64)
library(data.table)
library(lubridate)
library(openxlsx)
library(ggplot2)
library(zoo)

library(MASS)
library(Matrix)
library(lme4)
library(optimx)
library(dfoptim)

library(plyr)
#library(heavy) # rmnorm
library(coda) # HPD
options(scipen=999)

```

# twitter data 
### read in 
```{r}
tbl_2011 <-
    list.files(pattern = "*.csv") %>% 
    map_df(~read.csv(.))
tbl_2016 <-
    list.files(pattern = "*.csv") %>% 
    map_df(~read_csv(.))
```

### mutate year-month variable 
```{r}
#tbl_2011$id<-as.character(tbl_2011$id)
tbl_2011$ym<-str_sub(tbl_2011$date,1,7)
tbl_2011$ym<-as.Date(as.yearmon(tbl_2011$ym))
tbl_2016$ym<-str_sub(tbl_2016$date,1,7)
tbl_2016$ym<-as.Date(as.yearmon(tbl_2016$ym))
tbl_2011$date<-as.Date(tbl_2011$date)
tbl_2016$date<-as.Date(tbl_2016$date)
```

### twitter data and duma election 
```{r}
tbl_2011 %>%
  group_by(date) %>%
  dplyr::count() %>%
  ggplot+
  geom_point(aes(x = date, y=n))+
  labs(x = "Date", y = "Monthly observation of number of tweets")+
  theme_bw()+
  geom_vline(xintercept = as.numeric(as.Date('2011-12-14')), linetype=4)+
  annotate(geom = "text",
           label = c("2011 Duma Election"),
           x = as.Date('2011-12-28'),
           y = 8000)

tbl_2016 %>%
  group_by(date) %>%
  dplyr::count() %>%
  ggplot+
  geom_point(aes(x = date, y=n))+
  labs(x = "Date", y = "Monthly observation of number of tweets")+
  theme_bw()+
  geom_vline(xintercept = as.numeric(as.Date('2016-09-18')), linetype=4)+
  annotate(geom = "text",
           label = c("2016 Duma Election"),
           x = as.Date('2016-09-25'),
           y = 8000)
```

# protest data
### read in protest data 
```{r}
protest<-readxl::read_xlsx("Lankina__russia-protest-event--dataset-2007-2017.xlsx")
```

### national protest data 
```{r}
protest$date<-as.Date(protest$Date,format = "%Y-%m-%d")
protest$year<-str_sub(protest$date,1,4)
protest$month<-str_sub(protest$date,6,7)
protest$ym<-str_sub(protest$date,1,7)
protest$ym<-as.Date(as.yearmon(protest$ym))

protest %>%
  dplyr::count(ym) %>%
  ggplot()+
  geom_line(aes(x = ym, y = n, group=1)) +
  geom_vline(xintercept = as.numeric(as.Date('2016-09-01')), linetype=4)+
  geom_vline(xintercept = as.numeric(as.Date('2011-12-01')), linetype=4)+
  geom_vline(xintercept = as.numeric(as.Date('2007-12-01')), linetype=4)+
  annotate(geom = "text",
           label = c("2007 Duma","2011 Duma","2016 Duma"),
           x = c(as.Date('2008-09-01'),as.Date('2012-09-01'),as.Date('2016-01-01')),
           y = 150)+
  scale_y_continuous(limits = c(0, 150))+
  scale_x_date(date_breaks = "year" , date_labels = "%Y")+
  theme_bw()+
  labs(x = "Year-Month", y = "Monthly observations")

```

### protest data by oblast and time 
```{r}
protest %>%
  filter(`# protesters` >=20) %>%
  group_by(Region) %>%
  filter(n()!=1) %>%
  ggplot()+
  geom_line(aes(x = ym, y = `# protesters`)) +
  geom_vline(xintercept = as.numeric(as.Date('2016-09-01')), linetype=4)+
  geom_vline(xintercept = as.numeric(as.Date('2011-12-01')), linetype=4)+
  scale_x_date(date_breaks = "year" , date_labels = "%y")+
  labs(x = "Date", y = "Number of protesters in each protest")+
  facet_wrap(~Region, scales = "free_y",ncol = 7)

suppressMessages(print(by_region))
```


# Mobile cellular subscriptoion 
```{r}
mobile<-read.csv("./API_IT.CEL.SETS_DS2_en_csv_v2_3931323/API_IT.CEL.SETS_DS2_en_csv_v2_3931323.csv")

mobile %>%
  filter(Country.Name == "Russian Federation")
```


```{r}
write.csv(tw,"bots_training.csv")
write.csv(tbl,"bots_classification.csv")
```


